### ISSUE TITLE
Oh—man, where's the dashboard?

### ISSUE THREAD

**Issue by itsnamgyu** [SGCSRelease/ProjectsDjangoApp#2]
This Django app seems to be dependent on custom dashboard template files.

I think we'll need to provide some documentation on this or include the dashboard files within the repo.

Related server error:
```bash
Internal Server Error: /new/
Traceback (most recent call last):
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 109, in find_template
    template_name, skip=history,
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/engine.py", line 130, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dashboard/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/itsnamgyu/Code/rsop-front/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: dashboard/base.html
```

**Comment by tronze** [comment]
umm... not provided, so you have to use your own dashboard system.
